### ISSUE TITLE
Impossible d'ajouter des personnages à un groupe (existant ?)

### ISSUE THREAD

**Issue by Crocmagnon** [Crocmagnon/charasheet#24]
```
[2022-11-16 11:00:10,406 - ERROR - MainProcess/log.log_response:241] Internal Server Error: /party/2/change/
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/party/views.py", line 66, in party_change
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/app/venv/lib/python3.11/site-packages/django/forms/forms.py", line 437, in full_clean
    self._clean_fields()
  File "/app/venv/lib/python3.11/site-packages/django/forms/forms.py", line 449, in _clean_fields
    value = field.clean(value)
            ^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/django/forms/models.py", line 1596, in clean
    qs = self._check_values(value)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/django/forms/models.py", line 1621, in _check_values
    self.queryset.filter(**{key: pk})
  File "/app/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1419, in filter
    self._not_support_combined_queries("filter")
  File "/app/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1945, in _not_support_combined_queries
    raise NotSupportedError(
django.db.utils.NotSupportedError: Calling QuerySet.filter() after union() is not supported.
```

**Comment by vicolivry** [comment]
Ca fonctionne lorsqu'on invite les joueurs au moment de la creation du groupe. En revanche, on ne peut pas accéder aux profils en cliquant sur les cards des joueurs

`Not Found

The requested resource was not found on this server.`

Lorsque je clique sur le bouton "Observer"

**Comment by vicolivry** [comment]
"Gérer" fonctionne et "Observer" non, donc je pense que ca dépend de l'acceptation de l'invitation
